language: java

services:
  - docker

before_install:
  - docker pull elasticsearch:6.5.3
  - docker run -d -p 127.0.0.1:9200:9200 elasticsearch:6.5.3
#  - docker ps -a

install:
  - jdk_switcher use oraclejdk8
  #  - mvn verify -P 2-4-6
  #  - mvn verify -P 5-6-14
  - mvn verify -P 6-5-3